### ISSUE TITLE
Minswap `swapFee` and `returnLovelace`

### ISSUE THREAD

**Issue by nemo83** [bloxbean/jadex#7]
Hello,

Thank you very much for this library, looks very interesting and I'm studying the code.

I'm preparing my first swap and I stumbled upon `swapFee` and `returnLovelace`.

I know that `swapFee` can be hardcoded to 2 $ada or, follow [this formula](https://docs.minswap.org/min-token/usdmin-tokenomics/trading-fee-discount) for a discount, but I have no idea what `returnLovelace` is? How can I find it? Is there any utility in the code that can be used to calculate it?

Thanks in advance,
Gio

**Comment by stikkos** [comment]
Hello Gio,
Thank you for your message and I'm glad you find the library interesting!

The `swapFee` is indeed a fee applied to the swap operation.
As for `returnLovelace`, it represents the amount of ADA that will be returned along with the tokens after the swap. 
This is essential because native tokens cannot be transferred without a minimum amount of ADA accompanying them. 
Therefore, `returnLovelace` facilitate the transfer of the native tokens and is returned back to you.

Hope this helps and if you have specific questions or encounter challenges, don't hesitate to reach out.

Stik

<img width="391" alt="Screenshot 2024-01-16 at 11 47 17" src="https://github.com/bloxbean/jadex/assets/1133303/90ff3655-9248-4a2d-a0e7-dda84530e242">

On minswap this is called "Deposit ADA" (This amount of ADA will be held as minimum UTxO ADA and will be returned when your orders are processed or cancelled.)

**Comment by nemo83** [comment]
OK ok, thanks, so does it mean that I can safely set it to 2 ada.

These 2 ada will be sent to minswap and will come back along w/ the exchanged token, right?

**Comment by stikkos** [comment]
Yes, that is correct.

**Comment by nemo83** [comment]
Thanks, closing
